title: "Rahul Bhattacharya"
description: "Portfolio and blog of Rahul Bhattacharya â€” featuring projects, AI, and insights."

url: "https://rahulbhattacharya1.github.io"
baseurl: ""   # keep empty for user/org pages

sass:
  sass_dir: assets/css
  style: compressed

excerpt_separator: "\n\n"

incremental: true

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
paginate: 3
paginate_path: "/page:num"

timezone: "America/Chicago"
future: false
markdown: kramdown
kramdown:
  input: GFM
