title: "Rahul Bhattacharya"
sass:
  sass_dir: assets/css

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 3
paginate_path: "/page:num/"
